config/routes.rb
TorrentScraper::Application.routes.draw do

  root :to => "torrents#index"
  
  resources :torrents, :only => [:index] do
    collection do
      delete :destroy
      post :download
      scope ':tracker_id/:tracker_category_id' do
        post :sort
        post :search
      end
    end
  end

  resources :trackers
  match "media_categories/create" => "trackers#create_media_category", :as => :create_media_category

end

app/models/torrent.rb
class Torrent < ActiveRecord::Base

  belongs_to :tracker_category
  belongs_to :tracker
  belongs_to :media_category

  validates_presence_of :title, :link, :seeders
  validates_uniqueness_of :link
  validate :check_torrent

  @@seeders_limit = 5
  cattr_accessor :seeders_limit

  scope :for_tracker, ->(tracker) { tracker.blank? ? scoped : joins(:tracker_category).where("tracker_categories.tracker_id = ?", tracker.to_param) }
  scope :for_category, ->(category) { category.blank? ? scoped : where("torrents.tracker_category_id = ?", category.to_param) }
  
  scope :search, lambda { |terms|    
    return scoped unless terms
    relation = scoped.clone
    terms.reject {|k, v| v.blank? }.each do |column, value|
      relation &= where("torrents.#{column} LIKE ?", "%#{value}%")
    end
    relation
  }

  scope :ordered, lambda { |column, order|
    return scoped if column.blank? or order.blank?
    order("torrents.#{column} #{order}")
  }

  class << self
    def mark_as_deleted!(torrent_ids)
      process_torrents(torrent_ids) { |torrent| torrent.mark_as_deleted! }
    end
    
    def download!(torrent_ids)
      process_torrents(torrent_ids) { |torrent| torrent.download! }
    end
    
    private
    
    def process_torrents(torrent_ids, &block)
      torrents = Torrent.where("torrents.id IN (?)", Array.wrap(torrent_ids)).all
      torrents.each { |torrent| block.call(torrent) }
    end
  end
  
  delegate :origin_url, :url, :to => :tracker, :prefix => true

  def check_torrent
    errors.add(:title, "is low-quality!") if title.present? and title =~ /camrip|telesynch/i
    errors.add(:seeders, "not enough!") if seeders.present? and seeders < @@seeders_limit
  end

  def new?
    created_at == Date.today and not downloaded
  end

  def download!
    tracker.get_scraper.download_torrent!(self)
    self.update_attributes(:downloaded => true)
  end

  def mark_as_deleted!
    self.deleted = true
    save!
  end


end

app/controllers/torrents_controller.rb
class TorrentsController < ApplicationController
  DEFAULT_FILTER = { "date" => "today", "state" => "pending" }

  def index
  end

  def download
    Torrent.download!(params[:ids])
  end

  def sort
    respond_to do |format|
      format.js { render torrents }
      format.html { render :index }
    end
  end

  def search
    respond_to do |format|
      format.js { render torrents }
      format.html { render :index }
    end
  end

  def destroy
    Torrent.mark_as_deleted!(params[:ids])
  end

  private
  
  def torrents
    return @torrents if defined? @torrents
    torrents = Torrent.for_tracker(params[:tracker_id]).for_category(params[:tracker_category_id]).search(params[:search]).ordered(params[:column], params[:order])
    @torrents = Filter.instance.filter(torrents, DEFAULT_FILTER.merge(params))
    @torrents
  end
  helper_method :torrents
  
end

app/helpers/torrents_helper.rb
module TorrentsHelper

  def trackers
    Tracker.all
  end

  def filter_select(name)
    filter_name = "#{name}_filter"
    result = ""
    begin
      available_filters = eval("#{filter_name.classify}::AVAILABLE_FILTERS")
      result = select_tag filter_name, options_for_select(available_filters), :id => filter_name, :class => "filter", "data-name" => name
    rescue NameError
      Rails.logger.warn("Retrieve available filter values failed")
    end
    raw result
  end
  
  def torrents_for_tracker(tracker)
    torrents.select { |torrent| torrent.tracker_id == tracker.id }
  end
  
  def torrents_for_tracker_and_tracker_category(tracker, tracker_category)
    torrents.select { |torrent| torrent.tracker_id == tracker.id && torrent.tracker_category_id == tracker_category.id }
  end

end

app/views/torrents/_actions.html.haml
%span#actions
  %span.label= "Actions: "
  = link_to "Download", download_torrents_path, :request => :post, :class => "remote action download group with_text"
  = link_to "Delete", torrents_path, :request => :delete, :class => "remote action delete group with_text"

app/views/torrents/_torrent.html.haml
%tr[torrent]{ "data-id" => torrent.id }
  %td.checkbox= check_box_tag "select_torrent_#{torrent.to_param}", 1, false, :class => "select_torrent", :id => "select_torrent_#{torrent.to_param}", "data-id" => torrent.to_param
  %td.title= link_to torrent.title, torrent.tracker_link, :title => torrent.title
  %td.seeders= torrent.seeders
  %td.size= number_to_human_size torrent.size
  %td.actions
    = remote_link_to_download torrent
    = remote_link_to_delete_torrent torrent

app/views/torrents/_torrents.html.haml
- trackers.each do |tracker|
  .memorized.spoiler[tracker]
    .caption
      = tracker.name
    .content
      - if torrents_for_tracker(tracker).empty?
        %p= "No torrents yet..."
      = render :partial => "tracker_category", :collection => tracker.tracker_categories, :locals => { :tracker => tracker }

app/views/torrents/_tracker_category.html.haml
- if torrents.for_tracker(tracker).for_category(tracker_category).any?
  .spoiler.expanded[tracker_category]{ "data-id" => tracker_category.id }
    %h3.caption
      %span.toggler
      %span.title= tracker_category.media_category_name
    .tbl.content
      %table
        - table_header(tracker, tracker_category) do |t|
          = t.column check_box_tag(tracker_category.id, 1, false, :class => "select_tracker_category_torrents", :id => "select_tracker_category_#{tracker_category.id}_torrents"), :class => "checkbox", :width => 26
          = t.sortable_column :title, :searchable => true
          = t.sortable_column :seeders, :width => 80, :align => :right
          = t.sortable_column :size,    :width => 80, :align => :right
          = t.column "",                :width => 50, :align => :right
        %tbody
          = render torrents_for_tracker_and_tracker_category(tracker, tracker_category)

app/views/torrents/destroy.js.erb
$("div#torrents").html("<%= escape_javascript(render "torrents", :torrents => torrents) %>");

app/views/torrents/download.js.erb
$("div#torrents").html("<%= escape_javascript(render :partial => "torrents", :torrents => torrents) %>");

app/views/torrents/index.html.haml
- content_for :javascripts do
  = javascript_include_tag "sort_and_search", "spoiler", "copy", "actions"
%h1= "Torrents"
#toolbar
  %div{ :id => "filters", :data => { :url => torrents_path } }
    %span.label= "Filter:"
    = filter_select :date
    = filter_select :state
  = render "actions"
  #copy_destination
    %span.label= "Destination folder: "
    = text_field_tag "destination", cookies[:copy_destination], :id => "copy_destination_folder"
#torrents.content
  = render "torrents", :torrents => torrents

app/views/torrents/index.js.erb
$("div#torrents.content").html("<%= escape_javascript(render "torrents", :torrents => torrents) %>");